// User API Requests
// user obj schema : {username, password, age}


###
GET http://localhost:4000/user-api/users

###
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "username":"bhanu",
  "password":"bhanu",
  "age":20
}
###


GET http://localhost:4000/user-api/users/697f8d767342a5275e948232

###

PUT http://localhost:4000/user-api/users/697f8d767342a5275e948232
Content-Type: application/json

{
  "username":"bhanu",
  "password":"bhanu",
  "age":22
}

###
DELETE http://localhost:4000/user-api/users/697f8d767342a5275e948232

###

// Product API Requests
// product obj schema : {pid, productname, Price}
// 1. post / products 
// 2. get / products 
// 3. get / products/:id 
// 4. put / products/:id 

###
GET http://localhost:4000/product-api/products

###
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
  "pid":1001,
  "productname":"Laptop",
  "Price":"50000"
}

###
GET http://localhost:4000/product-api/products/697f8abde0e291640ff73374

###
PUT http://localhost:4000/product-api/products/697f8abde0e291640ff73374
Content-Type: application/json

{
  "pid":1001,
  "productname":"Gaming Laptop",
  "Price":"75000"
}
